[package]
name = "yamabiko"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
git2 = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
tempfile = "3.13"
rand = "0.8"
serde_yaml = { version = "0.9", optional = true }
log = { version = "0.4", optional = true }

[features]
full = ["log", "serde_yaml"]
yaml = ["serde_yaml"]

[dev-dependencies]
criterion = "0.4"
simple_logger = "4.0"

[[bench]]
name = "perf"
harness = false

[[bench]]
name = "queries"
harness = false

[lints]
workspace = true
