[package]
name = "yamabiko"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.15"
serde = "1.0"
chrono = "0.4"
tempfile = "3.3"
blake3 = "1.3"
rand = "0.8"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "perf"
harness = false

[profile.bench]
debug = true

