[package]
name = "ymbk"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
yamabiko = { workspace = true }
clap = { version = "4.5.20", features = ["derive"] }
color-print = "0.3.7"
git2 = { workspace = true }
